ExternalConfigs:
   - generic
   - adaptations
   - scripts

Configurations:
#    - Name: Maui Runtime x86
#      FileName: maui-runtime-x86
#      Active: False
#      Architecture: i686
#      RepositoryArchitecture: i586
#      BootloaderTimeout: 0
#      BootloaderOptions: "quiet"
#      Kernel: kernel-adaptation-pc
#      Part: x86.partition
#      Inherit:
#          - Maui
#          - Maui OSTree Runtime x86
#          - SSSE3 enabled X86 architecture
#
#    - Name: Maui Runtime x86_64
#      FileName: maui-runtime-x86_64
#      Active: False
#      Architecture: x86_64
#      RepositoryArchitecture: x86_64
#      BootloaderTimeout: 0
#      BootloaderOptions: "quiet"
#      Kernel: kernel-adaptation-pc
#      Part: x86.partition
#      Inherit:
#          - Maui
#          - Maui OSTree Runtime x86_64
#          - SSSE3 enabled X86 architecture
#
#    - Name: Maui Development x86
#      FileName: maui-devel-x86
#      Active: False
#      Architecture: i686
#      RepositoryArchitecture: i586
#      BootloaderTimeout: 0
#      BootloaderOptions: "quiet"
#      Kernel: kernel-adaptation-pc
#      Part: x86.partition
#      Inherit:
#          - Maui
#          - Maui OSTree Development x86
#          - SSSE3 enabled X86 architecture
#
#    - Name: Maui Development x86_64
#      FileName: maui-devel-x86_64
#      Active: False
#      Architecture: x86_64
#      RepositoryArchitecture: x86_64
#      BootloaderTimeout: 0
#      BootloaderOptions: "quiet"
#      Kernel: kernel-adaptation-pc
#      Part: x86.partition
#      Inherit:
#          - Maui
#          - Maui OSTree Development x86_64
#          - SSSE3 enabled X86 architecture

    ### PC

    - Name: Maui x86 Virtual Machine
      FileName: maui-x86-vm
      Active: True
      Architecture: i686
      RepositoryArchitecture: i586
      Mic2Options: -o . -f maui_raw --pkgmgr=zypp --record-pkgs=name,url,content,license --logfile=maui-x86-vm.log
      BootloaderTimeout: 0
      BootloaderOptions: "quiet"
      Kernel: kernel-adaptation-pc
      Part: x86.partition
      Inherit:
          - Maui Desktop
          - Maui x86 Adaptation VM
          - SSSE3 enabled X86 architecture

    - Name: Maui x86_64 Virtual Machine
      FileName: maui-x86_64-vm
      Active: True
      Architecture: x86_64
      RepositoryArchitecture: x86_64
      Mic2Options: -o . -f maui_raw --pkgmgr=zypp --record-pkgs=name,url,content,license --logfile=maui-x86_64-vm.log
      BootloaderTimeout: 0
      BootloaderOptions: "quiet"
      Kernel: kernel-adaptation-pc
      Part: x86.partition
      Inherit:
          - Maui Desktop
          - Maui x86 Adaptation VM
          - SSSE3 enabled X86 architecture

    - Name: Maui x86 Live CD
      FileName: maui-x86-livecd
      Active: True
      Architecture: i686
      RepositoryArchitecture: i586
      Mic2Options: -o . -f maui_livecd --pkgmgr=zypp --record-pkgs=name,url,content,license --logfile=maui-x86-livecd.log
      Kernel: kernel-adaptation-pc
      Part: x86.partition
      Inherit:
          - Maui Desktop
          - Maui x86 Adaptation LiveCD
          - SSSE3 enabled X86 architecture

    - Name: Maui x86_64 LiveCD
      FileName: maui-x86_64-livecd
      Active: True
      Architecture: x86_64
      RepositoryArchitecture: x86_64
      Mic2Options: -o . -f maui_livecd --pkgmgr=zypp --record-pkgs=name,url,content,license --logfile=maui-x86_64-livecd.log
      Kernel: kernel-adaptation-pc
      Part: x86.partition
      Inherit:
          - Maui Desktop
          - Maui x86 Adaptation LiveCD
          - SSSE3 enabled X86 architecture

    ### SDK

    - Name: Maui x86 SDK
      FileName: maui-x86-sdk
      Active: True
      Architecture: i686
      RepositoryArchitecture: i586
      Mic2Options: -o . -f fs --pack-to=maui-x86-latest-sdk-rolling-chroot.tar.bz2 --pkgmgr=zypp --record-pkgs=name,url,content,license --logfile=maui-x86-sdk.log
      Kernel: kernel-adaptation-pc
      Part: x86.partition
      Inherit:
          - Maui SDK
          - Maui x86 Common
          - SSSE3 enabled X86 architecture

    - Name: Maui x86_64 SDK
      FileName: maui-x86_64-sdk
      Active: True
      Architecture: x86_64
      RepositoryArchitecture: x86_64
      Mic2Options: -o . -f fs --pack-to=maui-x86_64-sdk-rolling-chroot.tar.bz2 --pkgmgr=zypp --record-pkgs=name,url,content,license --logfile=maui-x86_64-sdk.log
      Kernel: kernel-adaptation-pc
      Part: x86.partition
      Inherit:
          - Maui SDK
          - Maui x86 Common

    ### ARM boards

    - Name: Maui for Raspberry Pi
      FileName: maui-armv6l-rpi
      Active: False
      BootloaderTimeout: 0
      BootloaderOptions: "quiet"
      Inherit:
          - Maui Core
          - Maui Adaptation Raspberry Pi

    ### ARM phones

    - Name: Maui for Google Nexus 4
      FileName: maui-armv7hl-google-nexus4
      Active: False
      Inherit:
          - Maui Core
          - Maui Adaptation Google Nexus 4

    - Name: Maui for Google Nexus 5
      FileName: maui-armv7hl-google-nexus5
      Active: True
      Inherit:
          - Maui Core
          - Maui Adaptation Google Nexus 5

    ### ARM tablets

    - Name: Maui for Google Nexus 7
      FileName: maui-armv7hl-google-nexus7
      Active: False
      Inherit:
          - Maui Core
          - Maui Adaptation Google Nexus 7
