ExternalConfigs:
   - generic
   - adaptations
   - adaptations/armv6l-brcm-raspberrypi
   - adaptations/armv7hl-asus-grouper
   - adaptations/armv7hl-lge-hammerhead
   - adaptations/armv7hl-lge-mako
   - adaptations/x86-livecd
   - adaptations/x86-sdk
   - adaptations/x86-vm
   - scripts

Configurations:
#    - Name: Maui Runtime x86
#      FileName: maui-runtime-x86
#      Active: False
#      Architecture: i686
#      RepositoryArchitecture: i586
#      BootloaderTimeout: 0
#      BootloaderOptions: "quiet"
#      Kernel: kernel-adaptation-pc
#      Part: x86.partition
#      Inherit:
#          - Maui
#          - Maui OSTree Runtime x86
#          - SSSE3 enabled X86 architecture
#
#    - Name: Maui Runtime x86_64
#      FileName: maui-runtime-x86_64
#      Active: False
#      Architecture: x86_64
#      RepositoryArchitecture: x86_64
#      BootloaderTimeout: 0
#      BootloaderOptions: "quiet"
#      Kernel: kernel-adaptation-pc
#      Part: x86.partition
#      Inherit:
#          - Maui
#          - Maui OSTree Runtime x86_64
#          - SSSE3 enabled X86 architecture
#
#    - Name: Maui Development x86
#      FileName: maui-devel-x86
#      Active: False
#      Architecture: i686
#      RepositoryArchitecture: i586
#      BootloaderTimeout: 0
#      BootloaderOptions: "quiet"
#      Kernel: kernel-adaptation-pc
#      Part: x86.partition
#      Inherit:
#          - Maui
#          - Maui OSTree Development x86
#          - SSSE3 enabled X86 architecture
#
#    - Name: Maui Development x86_64
#      FileName: maui-devel-x86_64
#      Active: False
#      Architecture: x86_64
#      RepositoryArchitecture: x86_64
#      BootloaderTimeout: 0
#      BootloaderOptions: "quiet"
#      Kernel: kernel-adaptation-pc
#      Part: x86.partition
#      Inherit:
#          - Maui
#          - Maui OSTree Development x86_64
#          - SSSE3 enabled X86 architecture

    ### PC

    - Name: Maui x86 Virtual Machine
      Active: False
      Inherit:
          - Maui Adaptation x86 VM

    - Name: Maui x86_64 Virtual Machine
      Active: False
      Inherit:
          - Maui Adaptation x86_64 VM

    - Name: Maui x86 Live CD
      Active: True
      Inherit:
          - Maui Adaptation x86 LiveCD

    - Name: Maui x86_64 LiveCD
      Active: True
      Inherit:
          - Maui Adaptation x86_64 LiveCD

    ### SDK

    - Name: Maui x86 SDK
      Active: True
      Inherit:
          - Maui Adaptation x86 SDK

    - Name: Maui x86_64 SDK
      Active: True
      Inherit:
          - Maui Adaptation x86_64 SDK

    ### ARM boards

    - Name: Maui for Raspberry Pi
      Active: True
      Inherit:
          - Maui Core
          - Maui Adaptation Raspberry Pi

    ### ARM phones

    - Name: Maui for LGE Nexus 4
      Active: False
      Inherit:
          - Maui Mobile
          - Maui Adaptation LGE Mako

    - Name: Maui for LGE Nexus 5
      Active: True
      Inherit:
          - Maui Mobile
          - Maui Adaptation LGE Hammerhead

    ### ARM tablets

    - Name: Maui for Asus Nexus 7 2012 WiFi
      Active: False
      Inherit:
          - Maui Mobile
          - Maui Adaptation Asus Grouper
