ExternalConfigs:
   - /usr/share/kickstarter-configs/mer
   - generic
   - adaptations
   - scripts

Configurations:
    - Name: Maui Runtime x86
      FileName: maui-runtime-x86
      Architecture: i686
      RepositoryArchitecture: i586
      BootloaderTimeout: 0
      BootloaderOptions: "quiet"
      Kernel: kernel-adaptation-pc
      Part: x86.partition
      Inherit:
          - Maui
          - Maui OSTree Runtime x86
          - SSSE3 enabled X86 architecture

    - Name: Maui Runtime x86_64
      FileName: maui-runtime-x86_64
      Architecture: x86_64
      RepositoryArchitecture: x86_64
      BootloaderTimeout: 0
      BootloaderOptions: "quiet"
      Kernel: kernel-adaptation-pc
      Part: x86.partition
      Inherit:
          - Maui
          - Maui OSTree Runtime x86_64
          - SSSE3 enabled X86 architecture

    - Name: Maui Development x86
      FileName: maui-devel-x86
      Architecture: i686
      RepositoryArchitecture: i586
      BootloaderTimeout: 0
      BootloaderOptions: "quiet"
      Kernel: kernel-adaptation-pc
      Part: x86.partition
      Inherit:
          - Maui
          - Maui OSTree Development x86
          - SSSE3 enabled X86 architecture

    - Name: Maui Development x86_64
      FileName: maui-devel-x86_64
      Architecture: x86_64
      RepositoryArchitecture: x86_64
      BootloaderTimeout: 0
      BootloaderOptions: "quiet"
      Kernel: kernel-adaptation-pc
      Part: x86.partition
      Inherit:
          - Maui
          - Maui OSTree Development x86_64
          - SSSE3 enabled X86 architecture

    - Name: Maui x86 Virtual Machine
      FileName: maui-x86-vm
      Architecture: i686
      RepositoryArchitecture: i586
      BootloaderTimeout: 0
      BootloaderOptions: "quiet"
      Kernel: kernel-adaptation-pc
      Part: x86.partition
      Inherit:
          - Maui
          - Maui x86 Adaptation VM
          - SSSE3 enabled X86 architecture

    - Name: Maui x86_64 Virtual Machine
      FileName: maui-x86_64-vm
      Architecture: x86_64
      RepositoryArchitecture: x86_64
      BootloaderTimeout: 0
      BootloaderOptions: "quiet"
      Kernel: kernel-adaptation-pc
      Part: x86.partition
      Inherit:
          - Maui
          - Maui x86 Adaptation VM
          - SSSE3 enabled X86 architecture

    - Name: Maui Adaptation Raspberry Pi
      FileName: maui-armv6l-rpi
      Architecture: armv6l
      RepositoryArchitecture: armv6l
      BootloaderTimeout: 0
      BootloaderOptions: "quiet"
      Inherit:
          - Maui
          - Maui Adaptation Raspberry Pi

    - Name: Maui Adaptation Google Nexus7
      FileName: maui-armv7hl-google-nexus7
      Architecture: armv7hl
      RepositoryArchitecture: armv7hl
      Inherit:
          - Maui
          - Maui Adaptation Google Nexus7
